name: Monitor SIPAC UFPB (Telegram)

on:
  schedule:
    - cron: '0 */1 * * *' # Roda a cada hora
  workflow_dispatch:

jobs:
  check_sipac:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar Script
        env:
          # AQUI MUDOU: Pegamos as chaves do Telegram
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit e Push do status atualizado
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add last_state.json
          git commit -m "Update last state [skip ci]" || exit 0
          git push
