name: Monitor SIPAC UFPB (Telegram)

on:
  schedule:
    - cron: '0 */4 * * *' # Roda a cada 4 horas
  workflow_dispatch:

jobs:
  check_sipac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar Script
        env:
          # AQUI MUDOU: Pegamos as chaves do Telegram
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
